global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: dummy
  honor_timestamps: true
  metrics_path: /metrics
  static_configs:
  - targets:
    - dummy:8080